version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - frontend_venv:/app/.venv
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}

volumes:
  frontend_venv:
  backend_venv: